# 1. The address of your database (Make sure you created 'waterquality' in pgAdmin!)
spring.datasource.url=jdbc:postgresql://localhost:5432/waterquality
spring.datasource.username=postgres
spring.datasource.password=12345

# 2. This magic line tells Spring to automatically create the tables for you!
spring.jpa.hibernate.ddl-auto=update

# 3. This shows you the SQL commands in the console (useful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Increase max upload size for AI Image Scanner
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB